<a href="https://colab.research.google.com/github/JavZon/Deep-Learning/blob/main/Deep_Learning_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow import keras

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import Accuracy

In [6]:
# Defining a simple model

model=Sequential([
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# compile model

model.compile(
    optimizer=Adam(),
    loss=CategoricalCrossentropy(),
    metrics=['accuracy']
)

In [17]:
model

<Sequential name=sequential_2, built=False>

In [18]:
print(f'Model loss', model.loss)
print(f'Model optimizer', model.optimizer)

Model loss <keras.src.losses.losses.CategoricalCrossentropy object at 0x77ff5a3ad720>
Model optimizer <keras.src.optimizers.adam.Adam object at 0x77ff5a3ad900>


In [7]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Load Data from MNIST

In [8]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [11]:
# shape of train_images

print(train_images.shape)
print(len(train_images.shape))

(60000, 28, 28)
3


In [14]:
# shape of test_images

print(test_images.shape)
print(len(test_images.shape))

(10000, 28, 28)
3


In [41]:
import numpy as np
test_images.ndim

2

In [13]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [16]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

Model Building

In [26]:
model=Sequential([
    Dense(512, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='rmsprop',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model

<Sequential name=sequential_4, built=False>

In [27]:
print(f'Model loss', model.loss)
print(f'Model optimizer', model.optimizer)

Model loss sparse_categorical_crossentropy
Model optimizer <keras.src.optimizers.rmsprop.RMSprop object at 0x77ff5a5436d0>


In [28]:
#Reshaping images
train_images = train_images.reshape((60000, 28 * 28))
test_images = test_images.reshape((10000, 28 * 28))

In [45]:
train_images[0]

array([0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e

In [46]:
#Normalization
train_images = train_images.astype("float32") / 255
test_images = test_images.astype("float32") / 255

In [32]:
history = model.fit(train_images, train_labels, epochs=5, batch_size=128)
steps_per_epoch = len(train_images) // 128
print(f"Number of batches (steps per epoch): {steps_per_epoch}")

Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.1622 - loss: 2.2797
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5327 - loss: 1.8688
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.7276 - loss: 1.1458
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8008 - loss: 0.7993
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8345 - loss: 0.6316
Number of batches (steps per epoch): 468


In [33]:
# prediction
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([4.6407062e-04, 4.2068772e-05, 8.3063191e-05, 1.0002000e-03,
       9.7459136e-04, 1.5241146e-03, 6.0139105e-06, 9.6998167e-01,
       2.9531619e-04, 2.5628880e-02], dtype=float32)

In [36]:
#Model evaluation with unseen data
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")
print(f'test_loss:',test_loss)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8313 - loss: 0.5983
test_acc: 0.8553000092506409
test_loss: 0.5386177897453308


In [37]:
469*128

60032

In [38]:
60000/128

468.75

In [ ]:
Epoch 1/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.1622 - loss: 2.2797
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5327 - loss: 1.8688
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.7276 - loss: 1.1458
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8008 - loss: 0.7993
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.8345 - loss: 0.6316